<?php

namespace Database\Seeders;

use App\Models\Country;
use App\Models\Destination;
use App\Models\DestinationType;
use Illuminate\Database\Seeder;

class DestinationSeeder extends Seeder
{
    public function run(): void
    {
        $countries = Country::query()->pluck('id', 'iso_code');
        $types = DestinationType::query()->pluck('id', 'code');

        foreach ($this->destinations() as $item) {
            $countryIso = $item['country_iso'];
            $typeCodes = $item['types'];
            unset($item['country_iso']);
            unset($item['types']);

            $destination = Destination::updateOrCreate(
                ['name' => $item['name']],
                [
                    ...$item,
                    'country_id' => $countries->get($countryIso),
                ],
            );

            $destination->types()->sync(
                collect($typeCodes)->map(fn (string $code) => $types->get($code))->filter()->values()->all(),
            );
        }
    }

    /**
     * @return array<int, array<string, mixed>>
     */
    private function destinations(): array
    {
        return [
            ['name' => 'Barcelona', 'country_iso' => 'ES', 'latitude' => 41.3874, 'longitude' => 2.1686, 'flight_hours_from_vienna' => 2.4, 'description_sk' => 'Katalánska metropola spája mestské pamiatky, Gaudího architektúru a pláže pri Stredozemnom mori.', 'image_url' => 'https://images.contentstack.io/v3/assets/blt06f605a34f1194ff/blt98aab8678ac3bce7/663907b78447cbf1b69ca84f/logan-armstrong-hVhfqhDYciU-unsplash-edited-MOBILE-HEADER.jpg?fit=crop&disable=upscale&auto=webp&quality=60&crop=smart', 'types' => ['sea_beach', 'historic', 'city_break']],
            ['name' => 'Palma de Mallorca', 'country_iso' => 'ES', 'latitude' => 39.5696, 'longitude' => 2.6502, 'flight_hours_from_vienna' => 2.4, 'description_sk' => 'Slnečné Baleáry s plážami, prístavom a gotickou katedrálou v kompaktnom centre.', 'image_url' => 'https://cabauhotels.com/wp-content/uploads/2025/08/cathedral-de-palma-de-mallorca.webp', 'types' => ['sea_beach', 'city_break']],
            ['name' => 'Nice', 'country_iso' => 'FR', 'latitude' => 43.7102, 'longitude' => 7.2620, 'flight_hours_from_vienna' => 1.8, 'description_sk' => 'Azúrové pobrežie s promenádou, starým mestom a ľahkým výletom do Monaka či Cannes.', 'image_url' => 'https://www.franceguide.info/wp-content/uploads/sites/18/nice_ss.jpg', 'types' => ['sea_beach', 'city_break']],
            ['name' => 'Split', 'country_iso' => 'HR', 'latitude' => 43.5081, 'longitude' => 16.4402, 'flight_hours_from_vienna' => 1.3, 'description_sk' => 'Dalmátske mesto pri mori s Diokleciánovým palácom a ostrovmi na dosah trajektom.', 'image_url' => 'https://gotripzi.com/cdn-cgi/image/onerror=redirect,width=3200,height=2400,fit=cover,format=png/_astro/split-hr-city.D_xGwkjt.webp', 'types' => ['sea_beach', 'historic']],
            ['name' => 'Mykonos', 'country_iso' => 'GR', 'latitude' => 37.4467, 'longitude' => 25.3289, 'flight_hours_from_vienna' => 2.3, 'description_sk' => 'Kykladský ostrov s bielymi uličkami, veternými mlynmi a živými plážami.', 'image_url' => 'https://cdn1.travala.com/wp-content/uploads/2020/03/Mykonos.jpg', 'types' => ['sea_beach']],
            ['name' => 'Antalya', 'country_iso' => 'TR', 'latitude' => 36.8969, 'longitude' => 30.7133, 'flight_hours_from_vienna' => 2.6, 'description_sk' => 'Turecká riviéra ponúka teplé more, all-inclusive rezorty a historické centrum Kaleici.', 'image_url' => 'https://www.travelassistant24.com/operation/blog_images/best-of-antalya.jpg', 'types' => ['sea_beach', 'historic']],
            ['name' => 'Hurghada', 'country_iso' => 'EG', 'latitude' => 27.2579, 'longitude' => 33.8116, 'flight_hours_from_vienna' => 3.8, 'description_sk' => 'Letovisko pri Červenom mori s celoročným teplom, koralmi a výbornými podmienkami na šnorchlovanie.', 'image_url' => 'https://c.ccdn.sk/21476/uploads/fs_images/contentnews/106/dovolenka-hurghada_395_o.jpg', 'types' => ['sea_beach', 'adventure']],
            ['name' => 'Dubrovník', 'country_iso' => 'HR', 'latitude' => 42.6507, 'longitude' => 18.0944, 'flight_hours_from_vienna' => 1.4, 'description_sk' => 'Historické hradby nad Jadranom, kamenné uličky a výhľady z lanovky na Srď.', 'image_url' => 'https://www.fischer.sk/getmedia/043290bc-14d8-42fc-a687-df87e10368fe/dubrovnik-0_1200x0.jpg.aspx?maxsidesize=1200&resizemode=force', 'types' => ['sea_beach', 'historic']],
            ['name' => 'Innsbruck', 'country_iso' => 'AT', 'latitude' => 47.2692, 'longitude' => 11.4041, 'flight_hours_from_vienna' => 1.0, 'description_sk' => 'Alpské mesto s lanovkami priamo z centra, zimnými športmi a výhľadmi na Nordkette.', 'image_url' => 'https://www.visitaustria.info/en/wp-content/uploads/sites/171/innsbruck-river-hd.jpg', 'types' => ['mountains', 'city_break']],
            ['name' => 'Chamonix', 'country_iso' => 'FR', 'latitude' => 45.9237, 'longitude' => 6.8694, 'flight_hours_from_vienna' => 2.0, 'description_sk' => 'Ikonické horské stredisko pod Mont Blancom pre turistiku, lyžovanie a lanovku Aiguille du Midi.', 'image_url' => 'https://www.peakretreats.co.uk/media/oh5huxwy/chamonix-rafting.webp?width=952&height=660&v=1dbc50ab8de8fe0', 'types' => ['mountains', 'adventure']],
            ['name' => 'Zermatt', 'country_iso' => 'CH', 'latitude' => 46.0207, 'longitude' => 7.7491, 'flight_hours_from_vienna' => 2.2, 'description_sk' => 'Bezautové švajčiarske stredisko s výhľadom na Matterhorn a celoročnými horskými trasami.', 'image_url' => 'https://ca-times.brightspotcdn.com/dims4/default/a1ea1c3/2147483647/strip/true/crop/1600x1068+0+0/resize/1200x801!/quality/75/?url=https%3A%2F%2Fcalifornia-times-brightspot.s3.amazonaws.com%2F93%2F73%2Ff8cdbf69427bb67a4d444b990063%2Fswiss-zermatt-matterhorn-city-village.jpg', 'types' => ['mountains', 'adventure']],
            ['name' => 'Reykjavík', 'country_iso' => 'IS', 'latitude' => 64.1466, 'longitude' => -21.9426, 'flight_hours_from_vienna' => 4.3, 'description_sk' => 'Severská základňa pre gejzíry, vodopády, lávové polia a termálne kúpele.', 'image_url' => 'https://images.contentstack.io/v3/assets/blt06f605a34f1194ff/blte67f0786c0491036/687e464355acc485bfa5421d/einar-h-reynis-Y1MQ6zlQAj8-unsplash-header_mobile.jpg?fit=crop&disable=upscale&auto=webp&quality=60&crop=smart', 'types' => ['mountains', 'adventure', 'city_break']],
            ['name' => 'Bergen', 'country_iso' => 'NO', 'latitude' => 60.3913, 'longitude' => 5.3221, 'flight_hours_from_vienna' => 2.8, 'description_sk' => 'Nórske mesto medzi fjordmi a horami, známe dreveným nábrežím Bryggen.', 'image_url' => 'https://cdn.sanity.io/images/jlrwvnbf/production/1bd5824db550ed25de29090b5c31c167e7e82323-4426x2951.jpg?fp-x=0.7598282873926796&fp-y=0.5299898339545916&w=2048&h=1152&q=75&fit=crop&crop=focalpoint&auto=format', 'types' => ['mountains', 'historic']],
            ['name' => 'Tatranská Lomnica', 'country_iso' => 'SK', 'latitude' => 49.1667, 'longitude' => 20.2833, 'flight_hours_from_vienna' => 1.0, 'description_sk' => 'Vysokotatranská obec s prístupom na Skalnaté pleso, Lomnický štít a turistické chodníky.', 'image_url' => 'https://hotellomnicask.b-cdn.net/wp-content/webp-express/webp-images/uploads/2022/11/pohlad-na-vysoke-tatry-01-1024x436.jpg.webp', 'types' => ['mountains', 'adventure']],
            ['name' => 'Garmisch-Partenkirchen', 'country_iso' => 'DE', 'latitude' => 47.4917, 'longitude' => 11.0955, 'flight_hours_from_vienna' => 1.0, 'description_sk' => 'Bavorské horské mestečko pri Zugspitze s tiesňavou Partnachklamm a alpskou atmosférou.', 'image_url' => 'https://www.wikinger-reisen.de/bilder/reiseseiten/eibsee-mit-zugspitze-d25218-t.webp', 'types' => ['mountains', 'historic']],
            ['name' => 'Rím', 'country_iso' => 'IT', 'latitude' => 41.9028, 'longitude' => 12.4964, 'flight_hours_from_vienna' => 1.6, 'description_sk' => 'Večné mesto s Koloseom, fórami, fontánami a kuchyňou, ktorá funguje celoročne.', 'image_url' => 'https://www.bts.aero/content/destinations/12/rim-big.jpg', 'types' => ['historic', 'city_break']],
            ['name' => 'Atény', 'country_iso' => 'GR', 'latitude' => 37.9838, 'longitude' => 23.7275, 'flight_hours_from_vienna' => 2.1, 'description_sk' => 'Kolíska antiky s Akropolou, múzeami, tavernami a rýchlym prístupom k moru.', 'image_url' => 'https://www.satur.sk/media/cache/1920x675/page/2354_6481e3d8a1d02.jpeg', 'types' => ['historic', 'city_break']],
            ['name' => 'Praha', 'country_iso' => 'CZ', 'latitude' => 50.0755, 'longitude' => 14.4378, 'flight_hours_from_vienna' => 1.0, 'description_sk' => 'Historické centrum s Pražským hradom, Karlovým mostom a živou kaviarenskou scénou.', 'image_url' => 'https://cdn.kudyznudy.cz/files/1e/1e5055e1-be93-4470-97b9-8d16040373cd.webp?v=20221001055846', 'types' => ['historic', 'city_break']],
            ['name' => 'Krakov', 'country_iso' => 'PL', 'latitude' => 50.0647, 'longitude' => 19.9450, 'flight_hours_from_vienna' => 1.0, 'description_sk' => 'Poľské kultúrne mesto s Rynekom, Wawelom a štvrťou Kazimierz.', 'image_url' => 'https://cdn.obletsvet.cz/images/58fd6ae5-e2a4-4b80-916b-1968d9ecde54/rynek-glowny-11--w64.jpg', 'types' => ['historic', 'city_break']],
            ['name' => 'Istanbul', 'country_iso' => 'TR', 'latitude' => 41.0082, 'longitude' => 28.9784, 'flight_hours_from_vienna' => 2.3, 'description_sk' => 'Mesto medzi Európou a Áziou s mešitami, bazármi, Bosporom a bohatou gastronómiou.', 'image_url' => 'https://www.travel.sk/images/0x1080/turecko/istanbul/istanbul-mesto-tisicich-pribehov/istanbul-mesto-tisicich-pribehov-74b511.webp', 'types' => ['historic', 'city_break']],
            ['name' => 'Budapešť', 'country_iso' => 'HU', 'latitude' => 47.4979, 'longitude' => 19.0402, 'flight_hours_from_vienna' => 1.0, 'description_sk' => 'Dunajská metropola s termálnymi kúpeľmi, parlamentom a výraznou večernou atmosférou.', 'image_url' => 'https://cdn.pelipecky.sk/wp-content/uploads/2018/04/budapest.jpg', 'types' => ['historic', 'city_break']],
            ['name' => 'Edinburgh', 'country_iso' => 'GB', 'latitude' => 55.9533, 'longitude' => -3.1883, 'flight_hours_from_vienna' => 2.7, 'description_sk' => 'Škótske hlavné mesto s hradom, stredovekými uličkami a výstupom na Arthur’s Seat.', 'image_url' => 'https://media.cntraveller.com/photos/611be9e3d5b6f5a4a3def392/16:9/w_1280,c_limit/Mountain-view-over-city-Edinburgh-scotland-conde-nast-traveller-28july17-iStock.jpg', 'types' => ['historic', 'city_break', 'mountains']],
            ['name' => 'Lisabon', 'country_iso' => 'PT', 'latitude' => 38.7223, 'longitude' => -9.1393, 'flight_hours_from_vienna' => 3.5, 'description_sk' => 'Slnečné mesto na kopcoch s električkami, vyhliadkami, fado a výletmi k Atlantiku.', 'image_url' => 'https://loudavymkrokem.cz/wp-content/uploads/2024/12/Lisabon-1.jpg.webp', 'types' => ['historic', 'city_break', 'sea_beach']],
            ['name' => 'Paríž', 'country_iso' => 'FR', 'latitude' => 48.8566, 'longitude' => 2.3522, 'flight_hours_from_vienna' => 2.1, 'description_sk' => 'Klasický mestský výlet s múzeami, architektúrou, parkmi a večernými prechádzkami pri Seine.', 'image_url' => 'https://data.ceskekormidlo.cz/Zajezd/14177/142480.jpeg', 'types' => ['city_break', 'historic']],
            ['name' => 'Londýn', 'country_iso' => 'GB', 'latitude' => 51.5072, 'longitude' => -0.1276, 'flight_hours_from_vienna' => 2.5, 'description_sk' => 'Veľkomesto s múzeami, divadlami, trhmi, parkmi a ikonickými štvrťami.', 'image_url' => 'https://www.bts.aero/content/destinations/24/londyn-big.jpg', 'types' => ['city_break', 'historic']],
            ['name' => 'Amsterdam', 'country_iso' => 'NL', 'latitude' => 52.3676, 'longitude' => 4.9041, 'flight_hours_from_vienna' => 1.9, 'description_sk' => 'Kanály, bicykle, galérie a kompaktné centrum ideálne na predĺžený víkend.', 'image_url' => 'https://top20.amsterdam/images/things-to-do-in-amsterdam.webp', 'types' => ['city_break', 'historic']],
            ['name' => 'Berlín', 'country_iso' => 'DE', 'latitude' => 52.5200, 'longitude' => 13.4050, 'flight_hours_from_vienna' => 1.4, 'description_sk' => 'Kreatívna metropola s históriou 20. storočia, múzeami, hudbou a rozmanitými štvrťami.', 'image_url' => 'https://www.civitatis.com/f/alemania/berlin/berlin.jpg', 'types' => ['city_break', 'historic']],
            ['name' => 'Viedeň', 'country_iso' => 'AT', 'latitude' => 48.2082, 'longitude' => 16.3738, 'flight_hours_from_vienna' => 0.0, 'description_sk' => 'Elegantné mesto s palácmi, múzeami, kaviarňami a výbornou verejnou dopravou.', 'image_url' => 'https://my-utmost.com/img/rakusko/vieden/01.jpg', 'types' => ['city_break', 'historic']],
            ['name' => 'Kodaň', 'country_iso' => 'DK', 'latitude' => 55.6761, 'longitude' => 12.5683, 'flight_hours_from_vienna' => 1.8, 'description_sk' => 'Severské hlavné mesto s prístavom, cyklistikou, dizajnom a štvrťou Nyhavn.', 'image_url' => 'https://www.letenkyzababku.sk/wp-content/uploads/2015/05/9568217715_1017ebbc6f_o.jpg', 'types' => ['city_break']],
            ['name' => 'Štokholm', 'country_iso' => 'SE', 'latitude' => 59.3293, 'longitude' => 18.0686, 'flight_hours_from_vienna' => 2.2, 'description_sk' => 'Mesto na ostrovoch s historickým Gamla Stan, múzeami a blízkou prírodou.', 'image_url' => 'https://storage.kadetade.com/feature_image/4d6eb123-d786-4330-8d33-0632f7748d1c/show_big_Stockholm_hd_1.jpg', 'types' => ['city_break', 'historic']],
            ['name' => 'Dublin', 'country_iso' => 'IE', 'latitude' => 53.3498, 'longitude' => -6.2603, 'flight_hours_from_vienna' => 2.8, 'description_sk' => 'Írske hlavné mesto s literárnou históriou, pubmi, parkmi a výletmi na pobrežie.', 'image_url' => 'https://images.trvl-media.com/place/553248621555818193/7c32903c-f4b9-4e29-9af6-9d9ee5d425b7.jpg', 'types' => ['city_break', 'historic']],
            ['name' => 'Marrákeš', 'country_iso' => 'MA', 'latitude' => 31.6295, 'longitude' => -7.9811, 'flight_hours_from_vienna' => 3.8, 'description_sk' => 'Farebné marocké mesto so súkmi, palácmi, záhradami a bránou k Atlasu.', 'image_url' => 'https://i0.wp.com/mytravelation.com/wp-content/uploads/2024/05/Marrakesh.jpg?resize=724%2C483&ssl=1', 'types' => ['adventure', 'historic', 'city_break']],
            ['name' => 'Petra (Wadi Musa)', 'country_iso' => 'JO', 'latitude' => 30.3285, 'longitude' => 35.4444, 'flight_hours_from_vienna' => 3.6, 'description_sk' => 'Skalné mesto v Jordánsku s dramatickými kaňonmi, chrámami a púštnou krajinou.', 'image_url' => 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/0d/7a/45/44/treasury.jpg?w=600&h=-1&s=1', 'types' => ['adventure', 'historic']],
            ['name' => 'Madeira (Funchal)', 'country_iso' => 'PT', 'latitude' => 32.6669, 'longitude' => -16.9241, 'flight_hours_from_vienna' => 4.4, 'description_sk' => 'Atlantický ostrov s levádami, útesmi, subtropickou zeleňou a celoročnou turistikou.', 'image_url' => 'https://ber.berlin-airport.de/en/flying/airlines-ziele/inspiration-urlaub/dest-192-funchal/_jcr_content/root/responsivegrid/gallery_copy_2423635_1895900913/galleryimage_1707436834.coreimg.jpeg/1748584631076/2024-04-29-funchal-1.jpeg', 'types' => ['adventure', 'mountains', 'sea_beach']],
            ['name' => 'Tenerife (Costa Adeje)', 'country_iso' => 'ES', 'latitude' => 28.0866, 'longitude' => -16.7357, 'flight_hours_from_vienna' => 4.8, 'description_sk' => 'Kanársky ostrov s plážami, sopkou Teide a stabilným počasím počas väčšiny roka.', 'image_url' => 'https://www.cestee.sk/images/22/85/92285-2560.jpeg', 'types' => ['adventure', 'mountains', 'sea_beach']],
            ['name' => 'Kapadócia (Goreme)', 'country_iso' => 'TR', 'latitude' => 38.6431, 'longitude' => 34.8289, 'flight_hours_from_vienna' => 3.1, 'description_sk' => 'Rozprávková krajina tufových komínov, údolí a letov balónom nad Goreme.', 'image_url' => 'https://media-cdn.tripadvisor.com/media/attractions-splice-spp-674x446/14/cb/07/23.jpg', 'types' => ['adventure', 'historic']],
            ['name' => 'Benátky', 'country_iso' => 'IT', 'latitude' => 45.4408, 'longitude' => 12.3155, 'flight_hours_from_vienna' => 1.1, 'description_sk' => 'Lagúnové mesto s kanálmi, palácmi, ostrovmi a výraznou historickou atmosférou.', 'image_url' => 'https://www.letenkyzababku.sk/wp-content/uploads/2020/02/shutterstock_109982438-2.jpg', 'types' => ['historic', 'city_break', 'sea_beach']],
            ['name' => 'Sevilla', 'country_iso' => 'ES', 'latitude' => 37.3891, 'longitude' => -5.9845, 'flight_hours_from_vienna' => 3.1, 'description_sk' => 'Andalúzske mesto s Alcázarom, flamencovou kultúrou a teplými večermi v starom centre.', 'image_url' => 'https://images.winalist.com/blog/wp-content/uploads/2025/05/07154809/adobestock-167195068-1500x1039.jpeg', 'types' => ['historic', 'city_break']],
            ['name' => 'Valletta', 'country_iso' => 'MT', 'latitude' => 35.8997, 'longitude' => 14.5146, 'flight_hours_from_vienna' => 2.2, 'description_sk' => 'Maltské hlavné mesto s pevnosťami, prístavmi, kamennými ulicami a blízkymi zátokami.', 'image_url' => 'https://res.klook.com/image/upload/fl_lossy.progressive,q_60/Mobile/City/zueivkgiev9oglodjzf4.jpg', 'types' => ['historic', 'city_break', 'sea_beach']],
            ['name' => 'Ľubľana', 'country_iso' => 'SI', 'latitude' => 46.0569, 'longitude' => 14.5058, 'flight_hours_from_vienna' => 1.0, 'description_sk' => 'Kompaktné slovinské mesto s hradom, riekou Ljubljanica a rýchlym prístupom k Alpám aj jazerám.', 'image_url' => 'https://slevomat.sgcdn.cz/images/t/2000/18/22/18229354-83d076.webp', 'types' => ['city_break', 'historic', 'mountains']],
        ];
    }
}
